version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands: 
      - echo installing dependencies...
      - cd frontend && npm install

  build:
    commands:
      - echo building package
      - npm run build


artifacts: 
  discard-paths: yes
  files:
    - "frontend/build/**/*"